[build]
  publish = "dist"
  command = "bun run build"
  # Environment variables can be set in the Netlify UI (recommended for sensitive keys)
  # or defined here for non-sensitive build-time variables.
  # Example:
  # [build.environment]
  #   MY_VARIABLE = "my_value"

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.tsx"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.ts"
  [headers.values]
    Content-Type = "text/javascript"

[[headers]]
  for = "/*.mjs"
  [headers.values]
    Content-Type = "text/javascript"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200